"""create batches and consumption_records

Revision ID: 3b3b7932d5a1
Revises:
Create Date: 2025-12-11 23:41:35.499324

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b3b7932d5a1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_code", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=False),
        sa.Column("volume_liters", sa.Float(), nullable=False),
        sa.Column("fat_percent", sa.Float(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expiry", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_batches_batch_code"), "batches", ["batch_code"], unique=True
    )
    op.create_table(
        "consumption_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_records_batch_id"),
        "consumption_records",
        ["batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_consumption_records_batch_id"),
        table_name="consumption_records",
    )
    op.drop_table("consumption_records")
    op.drop_index(op.f("ix_batches_batch_code"), table_name="batches")
    op.drop_table("batches")
    # ### end Alembic commands ###
